# Generated by Django 4.2 on 2024-03-31 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bottle', editable=False, max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cap', editable=False, max_length=20)),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('quantity_per_bag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preform_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('size', models.IntegerField()),
                ('quantity_per_bag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shrinkwrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shrinkwrapper', editable=False, max_length=20)),
                ('product_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Preform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Preform', editable=False, max_length=30)),
                ('color', models.CharField(max_length=10)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.preform_type')),
            ],
        ),
    ]
