# Generated by Django 4.2 on 2024-03-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preform_type',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
