# Generated by Django 4.2 on 2024-04-04 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_capitem_remove_cap_color_delete_stockitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preform',
            name='color',
        ),
        migrations.CreateModel(
            name='ShrinkwrapperItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shrinkwrapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shrinkwrapper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreformItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=10)),
                ('preform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.preform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
