# Generated by Django 4.2 on 2024-04-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_preform_color_shrinkwrapperitem_preformitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitem',
            name='cap',
        ),
        migrations.RemoveField(
            model_name='preformitem',
            name='preform',
        ),
        migrations.RemoveField(
            model_name='shrinkwrapperitem',
            name='shrinkwrapper',
        ),
        migrations.AddField(
            model_name='capitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='capitem',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='capitem',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cap'),
        ),
        migrations.AddField(
            model_name='capitem',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.supplier'),
        ),
        migrations.AddField(
            model_name='preformitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='preformitem',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preformitem',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.preform'),
        ),
        migrations.AddField(
            model_name='preformitem',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.supplier'),
        ),
        migrations.AddField(
            model_name='shrinkwrapperitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shrinkwrapperitem',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shrinkwrapperitem',
            name='product_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shrinkwrapperitem',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.supplier'),
        ),
        migrations.AlterField(
            model_name='capitem',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='preformitem',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Shrinkwrapper',
        ),
    ]
