# Generated by Django 4.2 on 2024-04-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_capitem_cap_remove_preformitem_preform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('quantity', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('color', models.CharField(max_length=10, null=True)),
                ('product_type', models.CharField(max_length=20, null=True)),
                ('cap_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cap')),
                ('preform_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.preform')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.supplier')),
            ],
        ),
        migrations.RemoveField(
            model_name='preformitem',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='preformitem',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='shrinkwrapperitem',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='CapItem',
        ),
        migrations.DeleteModel(
            name='PreformItem',
        ),
        migrations.DeleteModel(
            name='ShrinkwrapperItem',
        ),
    ]
