# Generated by Django 4.2 on 2024-04-20 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_stockitem_remove_preformitem_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='cap_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cap'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='preform_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.preform_type'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='product_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
