# Generated by Django 4.2 on 2024-04-20 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_stockitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
