# Generated by Django 4.2 on 2024-04-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_stockitem_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('product_type', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.CharField(max_length=10)),
                ('cap_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cap')),
                ('preform_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.preform_type')),
            ],
        ),
    ]
