# Generated by Django 4.2 on 2024-04-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortages', models.IntegerField()),
                ('excesses', models.IntegerField()),
                ('damages', models.IntegerField()),
                ('waste_bottle', models.IntegerField()),
                ('good_bottle', models.IntegerField()),
                ('bottle_size', models.IntegerField()),
                ('bottle_color', models.IntegerField()),
                ('bottle_units', models.IntegerField()),
                ('product', models.ForeignKey(blank=True, limit_choices_to={'name': 'Preform'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.stock')),
            ],
        ),
    ]
