# Generated by Django 4.2 on 2024-04-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='color',
        ),
        migrations.AlterField(
            model_name='production',
            name='bottle_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
