# Generated by Django 4.2 on 2024-04-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_stockitem_color_alter_production_bottle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
