# Generated by Django 4.2 on 2024-05-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_sales_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='bottle_units',
        ),
        migrations.AddField(
            model_name='production',
            name='product_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
