# Generated by Django 4.2 on 2024-05-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_production_bottle_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='damages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='excesses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='shortages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='waste_bottle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
