# Generated by Django 4.2 on 2024-05-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_bottle_color_alter_production_bottle_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='color',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
