# Generated by Django 4.2 on 2024-05-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_stock_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
