# Generated by Django 4.2 on 2024-05-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_stock_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='bottle_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
