# Generated by Django 4.2 on 2024-05-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_stock_bottle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
