# Generated by Django 4.2 on 2024-05-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_stock_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
