# Generated by Django 4.2 on 2024-05-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_stock_unit_alter_stockitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
