# Generated by Django 4.2 on 2024-05-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_stockitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='quantity',
        ),
    ]
