# Generated by Django 4.2 on 2024-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_remove_stockitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
