# Generated by Django 4.2 on 2024-05-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_remove_stock_quantity_stockitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='excesses',
        ),
        migrations.RemoveField(
            model_name='production',
            name='shortages',
        ),
    ]
