# Generated by Django 4.2 on 2024-05-13 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_alter_ticket_records_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_records',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
