# Generated by Django 4.2 on 2024-05-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_alter_ticket_records_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_records',
            name='product_size',
        ),
    ]
