# Generated by Django 4.2 on 2024-05-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_remove_stock_notification_sent_delete_preform'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
