# Generated by Django 4.2 on 2024-05-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_alter_sales_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='bottle_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.color'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cap_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cap'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='preform_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.preform_type'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='cap_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cap'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.color'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='preform_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.preform_type'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.supplier'),
        ),
    ]
