# Generated by Django 4.2 on 2024-06-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_alter_production_bottle_color_alter_stock_cap_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='bottle_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
