# Generated by Django 4.2 on 2024-06-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_stockitem_bottle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='bottle_type',
        ),
    ]
