# Generated by Django 4.2 on 2024-06-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_alter_stockitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cap',
            name='name',
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
