# Generated by Django 4.2 on 2024-06-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_remove_cap_name_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cap_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
