# Generated by Django 4.2 on 2024-06-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_cap_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_unit', models.CharField(blank=True, max_length=30, null=True)),
                ('bottle_size', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('bottle_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.color')),
            ],
        ),
    ]
