# Generated by Django 4.2 on 2024-06-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_bottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
