# Generated by Django 4.2 on 2024-07-30 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_alter_purchase_created_at'),
        ('store', '0064_alter_stock_quantity_alter_stockitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('INCREASE', 'Increase'), ('DECREASE', 'Decrease')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.inventory')),
            ],
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='bottle_color',
        ),
        migrations.DeleteModel(
            name='Cap_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='production',
            name='bottle_color',
        ),
        migrations.RemoveField(
            model_name='production',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='cap_type',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='preform_type',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='cap_type',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='preform_type',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='ticket_records',
            name='product',
        ),
        migrations.DeleteModel(
            name='Bottle',
        ),
        migrations.DeleteModel(
            name='Cap',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Preform_type',
        ),
        migrations.DeleteModel(
            name='Production',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Ticket_Records',
        ),
    ]
