# Generated by Django 4.2.7 on 2024-09-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_rename_quantity_expense_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
