# Generated by Django 4.2.7 on 2024-09-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_alter_expense_category_alter_expense_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='decription',
            new_name='description',
        ),
    ]
