# Generated by Django 4.2 on 2024-07-13 12:18

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_ratio', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=5, max_length=8, prefix='pdt', unique=True)),
            ],
        ),
    ]
