# Generated by Django 4.2 on 2024-07-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_color_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_ratio',
        ),
    ]
