# Generated by Django 4.2 on 2024-07-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('grams', 'Grams'), ('kilogram', 'Kilogram'), ('millilitre', 'Millilitre'), ('centilitre', 'Centilitre'), ('litre', 'Litre'), ('millimeter', 'Millemeter')], max_length=20),
        ),
    ]
