# Generated by Django 4.2 on 2024-07-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'Kg'), ('mm', 'mm'), ('cl', 'Cl'), ('l', 'L'), ('ml', 'ml')], max_length=20),
        ),
    ]
