# Generated by Django 4.2 on 2024-07-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_alter_product_unit'),
        ('purchase', '0007_remove_inventory_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_preforms', models.PositiveIntegerField(default=0)),
                ('defective_preforms', models.PositiveIntegerField(default=0)),
                ('produced_bottles', models.PositiveIntegerField(default=0)),
                ('defective_bottles', models.PositiveIntegerField(default=0)),
                ('production_date', models.DateTimeField(auto_now_add=True)),
                ('preform_product', models.ForeignKey(limit_choices_to={'product__name': 'preform'}, on_delete=django.db.models.deletion.CASCADE, related_name='preform_productions', to='purchase.inventory')),
                ('produced_bottle_product', models.ForeignKey(limit_choices_to={'name': 'bottle'}, on_delete=django.db.models.deletion.CASCADE, related_name='bottle_productions', to='product.product')),
            ],
        ),
    ]
