# Generated by Django 4.2 on 2024-07-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
