# Generated by Django 4.2 on 2024-07-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchase_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
