# Generated by Django 4.2 on 2025-04-03 11:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_alter_product_unit'),
        ('sale', '0005_alter_sale_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PS_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_bags', models.PositiveIntegerField(default=0)),
                ('quantity_in_units', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='sale.customer')),
                ('product', models.ForeignKey(limit_choices_to={'name': 'preform'}, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='PS_RawMaterialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_bags', models.PositiveIntegerField()),
                ('quantity_in_units', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.customer')),
                ('product', models.ForeignKey(limit_choices_to={'name': 'preform'}, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='PS_Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_preforms', models.PositiveIntegerField(default=0)),
                ('defective_preforms', models.PositiveIntegerField(default=0)),
                ('produced_bottles', models.PositiveIntegerField(default=0)),
                ('defective_bottles', models.PositiveIntegerField(default=0)),
                ('production_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('preform_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preform_productions', to='production_services.ps_inventory')),
                ('produced_bottle_product', models.ForeignKey(limit_choices_to={'name': 'bottle'}, on_delete=django.db.models.deletion.CASCADE, related_name='ps_bottle_productions', to='product.product')),
            ],
        ),
    ]
