# Generated by Django 4.2 on 2025-04-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ps_rawmaterialreceipt',
            name='discount',
        ),
    ]
