# Generated by Django 4.2 on 2024-07-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='old_stock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
